---
platform: win64
generator-platform: x64
build_tool: vscode_cmake
build_type: Debug
vscode_exclude_from_workspace:
    - fips-glfw
    - fips-dawn
    - sokol-tools-bin
    - fips-utils
    - fips-libmodplug
    - fips-imgui
    - fips-cimgui
defines:
    USE_SOKOL_APP: ON
    SOKOL_USE_D3D11: ON
